name: HTML Validation

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
      - '.github/**'

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Get unzip
      run: | 
        sudo apt update
        sudo apt install unzip
        
    # - name: Download Nu HTML Validator
    #   run: |
    #     curl -L -o vnu.jar https://github.com/validator/validator/releases/download/latest/vnu.jar
    
    - name: Download Nu HTML Validator (v20.6.30)
      run: |
          curl https://github.com/validator/validator/releases/download/20.6.30/vnu.jar_20.6.30.zip
          unzip vnu.jar_20.6.30.zip
          mv dist/vnu.jar vnu.jar

    - name: Validate HTML files
      run: |
        echo "Validating HTML..."
        java -jar vnu.jar --errors-only ./
